### ISSUE TITLE
Dupe with protal

### ISSUE THREAD

**Issue by Shadow232** [Lunatrius/Stackie#4]
Steps how make dupe:
Firstly you have to create portal, for example to the Nether.
Secondly drop items ( for example 4 diamonds ) near or in the portal and after that go to nether dimension
In nether dimension you get duplicated items ( 8 diamonds )

Versions:
Forge - 1291
Stackie-1.7.10-1.6.0.33-universal
LunatriusCore-1.7.10-1.1.2.21-universal

**Comment by Lunatrius** [comment]
Confirmed, will try to debug and fix this later today.

**Comment by fkaa** [comment]
i also have this isue can you fix i ahve latest forge?
