### ISSUE TITLE
It seems silly but....

### ISSUE THREAD

**Issue by Crumbology** [Lunatrius/Stackie#6]
Was playing today and considered that a small stack(1 or 2 ingots) when walked on should give 1/2 a heart of damage when you stub your toe.  It was a joke, but seems like it could be a legitimate easter egg or feature, feel free to mock this suggestion. :)

**Comment by Lunatrius** [comment]
Might be a nice easter egg, but from the performance point of view it's anything but usable. Would have to track per player collisions with the items and make sure it only triggers once.

Doing this when picking up the stacks might be less intensive, but would negatively impact performance.

**Comment by Crumbology** [comment]
OK, thanks, didn't really expect it to be implemented, just seemed a good idea at the time.
