### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by WenXin20** [Lunatrius/Stackie#8]
forge 2026
Crash Report:
http://pastebin.com/wEBzRZRz

**Comment by Lunatrius** [comment]
Is the crash reproducible? Was it a one time crash or does it happen often (and how often)?

**Comment by WenXin20** [comment]
It happened once, and so far I haven't seen it happen again. I think I dropped some items on the ground when it crashed, but I'm not sure.

**Comment by Lunatrius** [comment]
I'll leave it open in case it happens again. Some mod is most likely tweaking the entity list in a separate thread, causing the crash.
